name: tests-auth

#when to run: only run test for corresponding service updating
on:
  pull_request:
    paths:
      - "auth/**"

# what to do when events tirggered
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm install && npm run test:ci
