name: tests-order

#when to run
on:
  pull_request
  
# what to do when events tirggered
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
