name: tests-tickets

#when to run
on:
  pull_request:
    paths:
      - 'tickets/**'
  
# what to do when events tirggered
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
