name: tests-payments
env:
  UDEMY_MICRO_SERVICES_STRIPE_SECRET: ${{ secrets.STRIPE_PUBLIC_KEY }}


#when to run
on:
  pull_request:
    paths:
      - 'payments/**'
  
# what to do when events tirggered
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
